### ISSUE TITLE
Flite reference

### ISSUE THREAD

**Issue by etosha** [syb0rg/tritium#2]
I think that you should reference your usage of flite (http://www.festvox.org/flite/) and that you should put back the flite copyright headers together with the original authors in all the flite files that you are using.

**Comment by syb0rg** [comment]
This project is based on the flite software, but all the files are created by me (not the authors of flite).  Crediting them with that work would be wrong.  I agree there should be a better reference back to that project, but putting that reference in every file seems to be a bit much.

**Comment by etosha** [comment]
I think removing the original author and copyright reference in every Flite file is a bit much. Attached is a diff between "your" cst_val_const.h and Flite version 1.4 cst_val_const.h

[diff_cst_val_const.h.txt](https://github.com/syb0rg/tritium/files/505721/diff_cst_val_const.h.txt)

This would probably hold for all "your" cst prefixed files.
